//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumMater2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string ID { get; set; }
        public string Content { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public string UserID { get; set; }
        public string PostID { get; set; }
        public string Approval { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
