//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumMater2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClubRole
    {
        public string UserID { get; set; }
        public string ClubID { get; set; }
        public short Role { get; set; }
        public System.DateTime DateTimeJoined { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual User User { get; set; }
    }
}
